spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  port: 9002

management:
  endpoints:
    web:
      exposure:
        include: health
