spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: local


---
server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: mrlii
    password: postgresdev
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

bytebites:
  jwt:
    secret: 18A2B3D4F5971C5E7F2A6D9B0C8E1A4F28B5E6D7G8H9J0K1L2M3N4P5Q6R7
    expiration: 86400000
    refresh-expiration: 604800000

management:
  endpoints:
    web:
      exposure:
        include: health,info