services:
  postgres:
    image: postgres:16-alpine
    container_name: bytebites-postgres
    environment:
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${db_name}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  restaurant-db:
    image: postgres:16-alpine
    container_name: bytebites-restaurant-db
    environment:
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${restaurant_db_name}
    ports:
      - "5433:5432"
    volumes:
      - restaurant-data:/var/lib/postgresql/data

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:3.6
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  order-db:
    image: postgres:16-alpine
    container_name: bytebites-order-db
    environment:
      POSTGRES_USER: ${db_username}
      POSTGRES_PASSWORD: ${db_password}
      POSTGRES_DB: ${order_db_name}
    ports:
      - "5434:5432"
    volumes:
      - order-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  restaurant-data:
  order-data: