spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: local

---
server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-public
          uri: lb://auth-service
          predicates:
            - Path=/auth/register,/auth/login,/auth/oauth2/**

        - id: auth-protected
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: JwtAuthenticationFilter

        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/restaurants/**
          filters:
            - name: JwtAuthenticationFilter
              args:
                publicPaths:
                  - /api/restaurants GET

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - name: JwtAuthenticationFilter
              args:
                publicPaths:
                  - /api/restaurants GET

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

bytebites:
  jwt:
    secret: ${ jwt_secret_key }

management:
  endpoints:
    web:
      exposure:
        include: health,info