spring:
  application:
    name: config-server
  profiles:
    active: local
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/bytebites-platform/config-repo
          clone-on-start: true
          default-label: main
        default-application-name: application

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90


management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh